default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= Rails.application.credentials.DB_CONNECTION_POOL || 5 %>
  username: <%= Rails.application.credentials.DB_USER || 'postgres' %>
  password: <%= Rails.application.credentials.DB_PASSWORD || 'postgres' %>

development:
  <<: *default
  host: <%= Rails.application.credentials.DB_HOST || 'localhost' %>
  database: simplero_test_development

test:
  <<: *default
  host: <%= Rails.application.credentials.DB_HOST || 'localhost' %>
  database: simplero_test_test

production:
  <<: *default
  host: <%= Rails.application.credentials.DB_HOST %>
  database: simplero_test_production
